# External systems
external.wsep.base-url=https://damp-lynna-wsep-1984852e.koyeb.app/
external.photon.base-url=https://photon.komoot.io/api/
external.photon.limit=1

# Startup behavior
startup.validate-external-systems=true


# Default admin created when no admins exist
system.default-admin.username=admin123
system.default-admin.password=password
system.default-admin.email=mail@example.com

# Virtual queue settings
virtual-queue.default-pass-num=50
virtual-queue.pass-timeout-ms=600000

# JWT settings
jwt.admin-secret=change-this-admin-secret-to-a-long-random-string-at-least-32-characters
jwt.user-expiration-ms=3600000
jwt.admin-expiration-ms=900000